version: "3.3"

services:
  redis:
    image: redis:alpine
    container_name: redis
    platform: linux/amd64
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass 123456
    volumes:
      - redis:/var/lib/redis/data
    networks:
        - redis

  mongodb:
    image: mongo:latest
    container_name: mongodb
    platform: linux/amd64
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=123456
    volumes:
      - mongodb:/data/db
    networks:
      - mongodb

  elasticsearch: 
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    container_name: elasticsearch
    platform: linux/amd64
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=123456
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - xpack.security.enabled=true
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    networks:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.2
    container_name: kibana
    platform: linux/amd64
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_USERNAME: elastic
      ELASTICSEARCH_PASSWORD: "123456"
    volumes:
      - elasticsearch:/usr/share/kibana/data
    networks:
      - elasticsearch

networks:
  redis:
    driver: "bridge"
  mongodb:
    driver: "bridge"
  elasticsearch:
    driver: "bridge"

volumes:
  redis:
  mongodb:
  elasticsearch: